Repository MuneebNasir/Amazin-online-bookstore-OA, pull requests merged in 2021-04, with the labels that each got.

#117 Add books real time
  src/main/js/pages/BookInterface/AddBookForm.js
  src/main/js/pages/BookInterface/Books.js
Labels: bug

#118 Additional Publisher UI Features
  src/main/js/Main.js
  src/main/js/pages/PublisherInterface/AddPublishersForm.js
  src/main/js/pages/PublisherInterface/PublisherSearchBar.js
  src/main/js/pages/PublisherInterface/Publishers.js
  src/main/js/pages/PublisherInterface/PublishersMenu.js
  src/main/js/pages/PublisherInterface/PublishersTable.js
  src/test/java/com/bookstore/controller/publisher/PublisherControllerTest.java
Labels: enhancement

#119 Firebase env variables
  package-lock.json
  package.json
  src/main/js/services/firebase/firebaseIndex.js
  webpack.config.js
Labels: new

#124 Firebase env variables
  .env
  .gitignore
  webpack.config.js
Labels: bug, new

#123 Added roles to database schema
  src/main/java/com/bookstore/jpa/role/Role.java
  src/main/java/com/bookstore/jpa/user/UserAccount.java
Labels: new

#126 Updated Author UI
  src/main/java/com/bookstore/controller/author/AuthorController.java
  src/main/java/com/bookstore/jpa/author/AuthorRepository.java
  src/main/js/Main.js
  src/main/js/pages/AuthorInterface/AddAuthorForm.js
  src/main/js/pages/AuthorInterface/AuthorGrid.js
  src/main/js/pages/AuthorInterface/AuthorSearchBar.js
  src/main/js/pages/AuthorInterface/Authors.js
  src/main/js/pages/AuthorInterface/AuthorsTable.js
  src/main/js/pages/PublisherInterface/PublishersTable.js
Labels: enhancement

#127 Added linking between book and author classes on the backend, and the…
  src/main/java/com/bookstore/controller/author/AuthorController.java
  src/main/java/com/bookstore/controller/book/BookController.java
  src/main/java/com/bookstore/jpa/author/Author.java
  src/main/java/com/bookstore/jpa/book/Book.java
  src/main/js/pages/BookInterface/AddBookForm.js
  src/test/java/com/bookstore/controller/author/AuthorControllerTest.java
  src/test/java/com/bookstore/controller/book/BookControllerTest.java
Labels: enhancement

#132 Role based authentication
  .babelrc
  package.json
  src/main/js/Main.js
  src/main/js/components/SignIn.js
  src/main/js/components/SignUp.js
  src/main/js/index.js
  src/main/js/pages/AuthorInterface/Authors.js
  src/main/js/pages/BookInterface/Books.js
  src/main/js/pages/PublisherInterface/Publishers.js
  src/main/js/services/firebase/authMethods.js
  src/main/js/services/firebase/firebaseIndex.js
  src/main/js/services/provider/AuthProvider.js
  src/main/js/services/provider/UserProvider.js
Labels: new

#128 Jaccard distance
  src/main/java/com/bookstore/controller/book/BookController.java
  src/main/java/com/bookstore/jpa/book/AgeGroup.java
  src/main/java/com/bookstore/jpa/book/Book.java
  src/main/java/com/bookstore/jpa/book/Genre.java
  src/main/java/com/bookstore/jpa/book/Length.java
  src/main/js/pages/BookInterface/BookInfoPopup.js
  src/main/js/pages/BookInterface/Books.js
  src/main/js/pages/BookInterface/BuyButton.js
Labels: enhancement

#134 Changed publication year so it doesn't add commas
  src/main/js/pages/BookInterface/BooksTable.js
Labels: bug

#139 Stop the useEffect from calling itself ad-infinum
  src/main/js/pages/BookInterface/AddBookForm.js
Labels: enhancement

#140 Properly pull Publisher names in the table, from the nested publisher…
  src/main/js/pages/BookInterface/Books.js
  src/main/js/pages/BookInterface/BooksTable.js
Labels: enhancement

#142 Update book table
  src/main/java/com/bookstore/controller/book/BookController.java
  src/main/js/pages/BookInterface/AddBookForm.js
  src/main/js/pages/BookInterface/BooksTable.js
Labels: new

#143 Add book form front end fixed to allow for ageGroup, length, genre
  src/main/java/com/bookstore/controller/book/BookController.java
  src/main/js/pages/BookInterface/AddBookForm.js
Labels: enhancement

#147 Adding Author and Publisher into Book Popup
  src/main/js/pages/BookInterface/BookInfoPopup.js
  src/main/js/pages/BookInterface/BooksTable.js
Labels: enhancement

#145 Only admins can remove books, publishers and authors from bookstore now
  src/main/js/pages/AuthorInterface/AuthorsTable.js
  src/main/js/pages/BookInterface/BooksTable.js
  src/main/js/pages/PublisherInterface/PublishersTable.js
Labels: bug

#148 Code Refactoring
  src/main/java/com/bookstore/controller/book/BookController.java
  src/main/java/com/bookstore/controller/publisher/PublisherController.java
  src/main/java/com/bookstore/jpa/book/Book.java
  src/main/java/com/bookstore/jpa/enums/Format.java
  src/main/java/com/bookstore/jpa/genre/Genre.java
  src/main/java/com/bookstore/jpa/genre/GenreRepository.java
  src/main/js/Main.js
  src/main/js/components/PageHeader.js
  src/main/js/pages/BookInterface/AddBookForm.js
  src/main/js/pages/BookInterface/BookInfoPopup.js
  src/main/js/pages/BookInterface/BookInformation.js
  src/main/js/pages/Home.js
  src/test/java/com/bookstore/controller/book/BookControllerTest.java
  src/test/java/jpa/BookTest.java
Labels: enhancement
