Repository MuneebNasir/Amazin-online-bookstore-OA, pull requests merged in 2021-03, with the labels that each got.

#13 Reorganized project packages to follow java convention
  src/main/java/com/bookstore/BookStoreApplication.java
  src/main/java/com/bookstore/jpa/author/Author.java
  src/main/java/com/bookstore/jpa/author/AuthorRepository.java
  src/main/java/com/bookstore/jpa/book/Book.java
  src/main/java/com/bookstore/jpa/book/BookRepository.java
  src/main/java/com/bookstore/jpa/publisher/Publisher.java
  src/main/java/com/bookstore/jpa/publisher/PublisherRepository.java
Labels: enhancement

#17 Create LICENSE
  LICENSE
Labels: new

#20 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: new, question

#26 Switch over the controllers, to use the spring-boot-start-data-rest
  pom.xml
  src/main/java/com/bookstore/jpa/DatabaseLoader.java
  src/main/java/com/bookstore/jpa/book/BookRepository.java
  src/main/resources/application.properties
Labels: enhancement

#32 Add Genre entity
  src/main/java/com/bookstore/jpa/Genre/Genre.java
  src/main/java/com/bookstore/jpa/Genre/GenreRepository.java
Labels: new

#34 Documentation Overview
  README.md
  doc/.github/CODE_OF_CONDUCT.md
  doc/.github/CONTRIBUTING.md
  doc/.github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, new

#38 Added a basic frontend implementation of react.
  package.json
  pom.xml
  src/main/java/com/bookstore/jpa/HomeController.java
  src/main/js/BookTable.js
  src/main/js/LeftDrawer.js
  src/main/js/app.js
  src/main/js/searchBar.js
  src/main/resources/templates/index.html
  webpack.config.js
Labels: new

#43 Create test database
  .gitignore
  .travis.yml
  package-lock.json
  src/main/resources/test.properties
Labels: enhancement

#49 Add Book Controller and its test cases.
  .travis.yml
  src/main/java/com/bookstore/controller/BookController.java
  src/main/java/com/bookstore/jpa/book/Book.java
  src/main/java/com/bookstore/jpa/book/BookRepository.java
  src/test/java/com/bookstore/controller/book/BookControllerTest.java
Labels: new

#50 Added forms to add and remove books from the bookstore.
  src/main/js/AddBookForm.js
  src/main/js/LeftDrawer.js
  src/main/js/RemoveBookForm.js
  src/main/js/app.js
Labels: enhancement

#30 Added User entity
  src/main/java/com/bookstore/jpa/user/User.java
  src/main/java/com/bookstore/jpa/user/UserRepository.java
Labels: new

#28 Added new Format entity
  .gitignore
  src/main/java/com/bookstore/controller/BookController.java
  src/main/java/com/bookstore/jpa/DatabaseLoader.java
  src/main/java/com/bookstore/jpa/book/Book.java
  src/main/java/com/bookstore/jpa/enums/Format.java
  src/test/java/com/bookstore/controller/book/BookControllerTest.java
Labels: new

#53 Create author controller
  src/main/java/com/bookstore/controller/author/AuthorController.java
  src/main/java/com/bookstore/jpa/author/Author.java
  src/main/java/com/bookstore/jpa/author/AuthorRepository.java
  src/main/java/com/bookstore/jpa/book/Book.java
  src/main/java/com/bookstore/utils/ObjectMapper.java
  src/main/java/com/bookstore/utils/StringUtility.java
  src/test/java/com/bookstore/book/AuthorControllerTest.java
  src/test/java/jpa/AuthorTest.java
Labels: enhancement, new

#54 Fixed endpoint calls from react
  package-lock.json
  src/main/java/com/bookstore/controller/BookController.java
  src/main/java/com/bookstore/jpa/DatabaseLoader.java
  src/main/java/com/bookstore/jpa/book/Book.java
  src/main/java/com/bookstore/jpa/user/UserAccount.java
  src/main/java/com/bookstore/jpa/user/UserAccountRepository.java
  src/main/java/com/bookstore/jpa/user/UserRepository.java
  src/main/js/AddBookForm.js
  src/main/js/BookTable.js
  src/main/js/RemoveBookForm.js
  src/main/js/app.js
  src/main/resources/application.properties
  src/test/java/com/bookstore/controller/book/BookControllerTest.java
Labels: bug, enhancement

#18 Publisher Rest API Controllers
  src/main/java/com/bookstore/controller/book/BookController.java
  src/main/java/com/bookstore/controller/publisher/PublisherController.java
  src/main/java/com/bookstore/jpa/publisher/Publisher.java
  src/main/java/com/bookstore/jpa/publisher/PublisherRepository.java
  src/test/java/com/bookstore/controller/book/BookControllerTest.java
  src/test/java/com/bookstore/controller/publisher/PublisherControllerTest.java
Labels: new

#63 Added uml class diagram
  doc/ClassDiagram/UML-Diagram.drawio
  doc/ClassDiagram/UML-Diagram.png
Labels: new

#66 Readme update
  README.md
Labels: documentation, enhancement

#73 Search and UI
  package-lock.json
  package.json
  src/main/java/com/bookstore/controller/book/BookController.java
  src/main/java/com/bookstore/controller/publisher/PublisherController.java
  src/main/js/Main.js
  src/main/js/app.js
  src/main/js/components/PageHeader.js
  src/main/js/index.js
  src/main/js/pages/About.js
  src/main/js/pages/BookInterface/AddBookForm.js
  src/main/js/pages/BookInterface/BookTable.js
  src/main/js/pages/BookInterface/LeftDrawer.js
  src/main/js/pages/BookInterface/RemoveBookForm.js
  src/main/js/pages/BookInterface/SearchBar.js
  src/main/js/pages/Home.js
  src/main/js/pages/PublisherInterface/Publishers.js
  src/main/js/pages/PublisherInterface/PublishersTable.js
  src/main/js/searchBar.js
  src/main/resources/templates/index.html
  src/test/java/com/bookstore/controller/publisher/PublisherControllerTest.java
  webpack.config.js
Labels: enhancement

#77 Publisher UI Development
  package-lock.json
  package.json
  src/main/js/Main.js
  src/main/js/pages/BookInterface/AddBookForm.js
  src/main/js/pages/PublisherInterface/AddPublishersForm.js
  src/main/js/pages/PublisherInterface/PublishersMenu.js
  webpack.config.js
Labels: new

#72 Moved ControllerTest and made JUnit test for Book
  src/test/java/com/bookstore/controller/author/AuthorControllerTest.java
  src/test/java/jpa/BookTest.java
Labels: enhancement, new

#81 Book Layout Revamp and Sorting
  package-lock.json
  package.json
  src/main/js/Main.js
  src/main/js/pages/BookInterface/BookGrid.js
  src/main/js/pages/BookInterface/BookInformation.js
  src/main/js/pages/BookInterface/BookTable.js
  src/main/js/pages/BookInterface/Books.js
  src/main/js/pages/BookInterface/BooksTable.js
  src/main/js/pages/BookInterface/RemoveBookForm.js
Labels: bug, enhancement, new

#80 Adding Notifications for Remove Books Requests
  src/main/js/pages/BookInterface/AddBookForm.js
  src/main/js/pages/BookInterface/BooksTable.js
  src/main/js/pages/PublisherInterface/AddPublishersForm.js
  src/main/js/pages/PublisherInterface/PublishersTable.js
Labels: enhancement

#83 Updating Package Json to Resolve Dependencies Issue
  package-lock.json
  package.json
Labels: bug

#84 Fixed the bug
  src/main/js/pages/BookInterface/BooksTable.js
Labels: bug

#85 Add author page
  src/main/js/Main.js
  src/main/js/pages/AuthorInterface/AddAuthorForm.js
  src/main/js/pages/AuthorInterface/AuthorGrid.js
  src/main/js/pages/AuthorInterface/Authors.js
  src/main/js/pages/AuthorInterface/AuthorsTable.js
Labels: new

#87 Fix reload glitch, by switching over to React-Dom HashRouter
  src/main/js/Main.js
  src/main/js/index.js
Labels: bug

#91 Accidentally removed the router links to Author - re-added them
  src/main/js/Main.js
Labels: bug

#93 This commit got out of hand
  package-lock.json
  package.json
  src/main/java/com/bookstore/controller/book/BookController.java
  src/main/java/com/bookstore/jpa/book/BookRepository.java
  src/main/js/pages/BookInterface/BookCart.js
  src/main/js/pages/BookInterface/BookInfoPopup.js
  src/main/js/pages/BookInterface/Books.js
  src/main/js/pages/BookInterface/BooksTable.js
  src/main/js/pages/BookInterface/BuyButton.js
  src/main/js/pages/BookInterface/SearchBar.js
  webpack.config.js
Labels: enhancement

#103 Improve author controller
  src/main/java/com/bookstore/controller/author/AuthorController.java
  src/main/java/com/bookstore/jpa/author/AuthorRepository.java
Labels: enhancement

#105 Updating Publisher Controller Endpoints to facilitate searching capabilities
  src/main/java/com/bookstore/controller/publisher/PublisherController.java
  src/main/java/com/bookstore/jpa/publisher/PublisherRepository.java
  src/main/js/pages/PublisherInterface/PublishersMenu.js
  src/main/js/pages/PublisherInterface/PublishersTable.js
Labels: enhancement

#113 Added test cases for author controller endpoints
  src/test/java/com/bookstore/controller/author/AuthorControllerTest.java
Labels: new

#114 updated uml class diagram
  doc/ClassDiagram/UML-Diagram.drawio
  doc/ClassDiagram/UML-Diagram.png
Labels: enhancement

#88 Sign in sign out
  .babelrc
  .gitignore
  package-lock.json
  package.json
  src/main/js/Main.js
  src/main/js/components/SignIn.js
  src/main/js/components/SignUp.js
  src/main/js/index.js
  src/main/js/services/firebase/authMethods.js
  src/main/js/services/firebase/firebaseIndex.js
  src/main/js/services/provider/AuthProvider.js
Labels: new

#116 Update README.md
  README.md
Labels: documentation
